<a href="https://colab.research.google.com/github/hermela-tt/SATC_Dialogue_Analytics/blob/main/SATC_Dialogue_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:

# Commit - Created using Colab, Initial project setup and SATC dataset exploration,


import pandas as pd


# Load the CSV directly (bc it's already uploaded to google Colab environment files on the left panel)
df = pd.read_csv('SATC_all_lines.csv')


# Quickly print shape and columns without heavy functions,  no buffering
print("Shape (Rows, Columns):", df.shape)
print("Columns:", list(df.columns))


# Show first 3 rows
display(df.head(3))




#cleaning preliminary


# missing values across all columns
print("\n Missing Values Per Column")
print(df.isnull().sum())


# check the top 15 unique speakers to see how characters are named
print("\n Top 15 Speakers by Dialogue Count ")


# Replace 'speaker' with your exact column name if it's capitalized differently (e.g., 'Speaker')
print(df["Speaker"].value_counts().head(15))




# drop null - remove rows where there is no character (speaker) or dialogue (line) to clean into a new dataframe (df_clean)
df_clean = df.dropna(subset=["Speaker", "Line"])


print(" \n Original rows: ", len(df))
print("\n Clean rows: ", len(df_clean))




# who talks the most


speaker_counts = df_clean["Speaker"].value_counts()


dialogue_share = (speaker_counts / speaker_counts.sum() * 100).round(2)


print(dialogue_share.head(10))




#checking total rows and values


#checking total number of rows by pulling bottom of dataset
df["Unnamed: 0"].tail()


#why does it reset
df["Unnamed: 0"].nunique()


#how many unique values, top 20 rows
df["Unnamed: 0"].head(20)


# how many unique value
df["Unnamed: 0"].nunique()


print ("\n ")
#fixing name inconsitences


# to stop mistakes - waring: A value is trying to be set on a copy of a slice from a DataFrame (Try using .loc[row_indexer,col_indexer] = value instead)
df_clean = df.dropna(subset=["Speaker", "Line"]).copy()
# remove spaces for speakers
df_clean["Speaker"] = df_clean["Speaker"].str.strip()


#are speaker names consistent
df_clean["Speaker"].unique()[:30]




#begin character analysis


# new dataframe for cleaned speaker column (without spaces), call first 15
df_clean["Speaker"].value_counts().head(15)




# Commit - Removed old code


# make sure we have a clean, duplicate copy
df_clean = df.copy()
print("Original rows:", len(df))
print("Clean copy rows:", len(df_clean))

# remove rows missing a speaker and line
df_clean = df_clean.dropna(subset=["Speaker", "Line"])

print("Rows after removing missing dialogue:")
print(len(df_clean))
#check mising or overlap (null) total in columns
df_clean.isnull().sum()

# (standardized) dropped index column (#)
df_clean = df_clean.drop(columns=["Unnamed: 0"])

print(df_clean.columns)


# to get total after cleaning new dataset
df_clean.nunique()

# to check on unique episode numbers
df_clean["Episode"].value_counts().sort_index()

# checking on why episodes end at
df_clean["Speaker"].value_counts().head(20)

Shape (Rows, Columns): (39999, 6)
Columns: ['Unnamed: 0', 'Season', 'Episode', 'Speaker', 'Line', 'date_job']

,Unnamed: 0,Season,Episode,Speaker,Line,date_job
0,0,1.0,1.0,Carrie,"Once upon a time, an English journalist came t...",NaN
1,1,1.0,1.0,Carrie,Elizabeth was attractive and bright.,NaN
2,2,1.0,1.0,Carrie,Right away she hooked up with one of the city'...,NaN

 Missing Values Per Column
Unnamed: 0        0
Season           10
Episode          11
Speaker         803
Line            788
date_job      39911
dtype: int64

 Top 15 Speakers by Dialogue Count
Speaker
Carrie       13941
Miranda       4780
Samantha      4067
Charlotte     3667
Big           1233
Steve          801
Aidan          703
Aleksandr      511
Trey           382
Stanford       367
Jack           364
Smith          222
Anthony        210
Richard        189
Robert         159
Name: count, dtype: int64

 Original rows:  39999

 Clean rows:  39195
Speaker
Carrie       35.57
Miranda      12.20
Samantha     10.38
Charlotte     9.36
Big           3.15
Steve         2.04
Aidan         1.79
Aleksandr     1.30
Trey          0.97
Stanford      0.94
Name: count, dtype: float64


Original rows: 39999
Clean copy rows: 39999
Rows after removing missing dialogue:
39195
Index(['Season', 'Episode', 'Speaker', 'Line', 'date_job'], dtype='object')

Speaker
Carrie        13941
Miranda        4780
Samantha       4067
Charlotte      3667
Big            1233
Steve           801
Aidan           703
Aleksandr       511
Trey            382
Stanford        367
Jack            364
Smith           222
Anthony         210
Richard         189
Robert          159
Harry           153
Harry           132
Bill Kelly      112
Skipper         103
Bunny           100
Name: count, dtype: int64